using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TutorFlow.Infrastructure.Persistence.Migrations
{
    // Removes column defaults that were never a modeled decision — each was
    // generated by an earlier migration's AddColumn(..., defaultValue: X)
    // call, needed only to satisfy NOT NULL on a column being added to a
    // table that (in a database with existing rows) would already have
    // data. No entity configuration ever declared HasDefaultValue for any
    // of these (confirmed: TutorFlowDbContextModelSnapshot.cs already
    // carries no default for them — the model's own understanding was
    // always "no default"; only the physical column definitions Npgsql
    // generated for AddColumn's defaultValue parameter were out of sync
    // with that). Since no database has ever held a row
    // (docs/phases/PHASE-02-REPORT.md, Section 3/6), dropping these is
    // free — no backfill, no data migration, nothing to reconcile.
    //
    // The ''-string default on Email/PasswordHash in particular was the one
    // worth closing while free: a genuine footgun (an account row that
    // silently satisfies NOT NULL with an empty, unusable credential
    // instead of failing loudly) that this phase's own instruction singled
    // out.
    /// <inheritdoc />
    public partial class RemoveMigrationArtifactColumnDefaults : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""ALTER TABLE "AuthTokens" ALTER COLUMN "AbsoluteExpiresAtUtc" DROP DEFAULT;""");
            migrationBuilder.Sql("""ALTER TABLE "Relationships" ALTER COLUMN "InvitedByAccountId" DROP DEFAULT;""");
            migrationBuilder.Sql("""ALTER TABLE "Tutors" ALTER COLUMN "Email" DROP DEFAULT;""");
            migrationBuilder.Sql("""ALTER TABLE "Tutors" ALTER COLUMN "PasswordHash" DROP DEFAULT;""");
            migrationBuilder.Sql("""ALTER TABLE "Students" ALTER COLUMN "Email" DROP DEFAULT;""");
            migrationBuilder.Sql("""ALTER TABLE "Students" ALTER COLUMN "PasswordHash" DROP DEFAULT;""");
            migrationBuilder.Sql("""ALTER TABLE "ParentGuardians" ALTER COLUMN "Email" DROP DEFAULT;""");
            migrationBuilder.Sql("""ALTER TABLE "ParentGuardians" ALTER COLUMN "PasswordHash" DROP DEFAULT;""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""ALTER TABLE "AuthTokens" ALTER COLUMN "AbsoluteExpiresAtUtc" SET DEFAULT '-infinity';""");
            migrationBuilder.Sql("""ALTER TABLE "Relationships" ALTER COLUMN "InvitedByAccountId" SET DEFAULT '00000000-0000-0000-0000-000000000000';""");
            migrationBuilder.Sql("""ALTER TABLE "Tutors" ALTER COLUMN "Email" SET DEFAULT '';""");
            migrationBuilder.Sql("""ALTER TABLE "Tutors" ALTER COLUMN "PasswordHash" SET DEFAULT '';""");
            migrationBuilder.Sql("""ALTER TABLE "Students" ALTER COLUMN "Email" SET DEFAULT '';""");
            migrationBuilder.Sql("""ALTER TABLE "Students" ALTER COLUMN "PasswordHash" SET DEFAULT '';""");
            migrationBuilder.Sql("""ALTER TABLE "ParentGuardians" ALTER COLUMN "Email" SET DEFAULT '';""");
            migrationBuilder.Sql("""ALTER TABLE "ParentGuardians" ALTER COLUMN "PasswordHash" SET DEFAULT '';""");
        }
    }
}
